site_name: BetonPortal

theme:
#  name: readthedocs
#  name: material
#  name: mkdocs
  name: lantana  # https://pawamoy.github.io/mkdocs-gallery/themes/lantana/
#  name: cosmo  # https://mkdocs.github.io/mkdocs-bootswatch/
  language: cs
  features:
    - navigation.tabs  # Adds main tabs
    - navigation.sections  # Creates collapsible sections
    - navigation.expand  # Keeps sidebar expanded
    - navigation.instant  # Instant navigation without full page reload
    - navigation.tracking  # Highlights the active section


markdown_extensions:
  - pymdownx.arithmatex:
      generic: true

extra_javascript:
  - javascripts/custom_js.js
  - javascripts/katex.js
  - https://unpkg.com/katex@0/dist/katex.min.js
  - https://unpkg.com/katex@0/dist/contrib/auto-render.min.js

extra_css:
  - stylesheets/extra.css
  - https://unpkg.com/katex@0/dist/katex.min.css




#nav:
#  - Home: index.md
#  - Průřez:
#      - Krytí: obecne/kryti.md